config/routes.rb
OctoDangerzone::Application.routes.draw do
  
  resources :galleries do
    resources :pictures
  end

  resources :posts do
    resources :comments
  end

  get 'tags/:tag' => 'posts#index', as: :tag

  get "home/index"

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :path => "d"
  resources :users
  
  get 'galleries/fragglerne', :as => 'fragglerne'

  namespace :admin do
  	match '/' => 'users#index'
  	resources :users
  end
  
   match '/profiles/dashboard' => 'profiles#dashboard', :as => :user_root
   resources :profiles, :only => [:dashboard]
  
   scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
   root :to => 'home#index'
 end
  
   match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
   match '', to: redirect("/#{I18n.default_locale}")
  
 
  

end

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  attr_accessible :content, :name, :title, :tag_list, :assets_attributes

  acts_as_taggable
  
  validates :name,  :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
                    
  has_many :comments, :dependent => :destroy

  has_many :assets
  accepts_nested_attributes_for :assets, :allow_destroy => true

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
   # GET /posts
  # GET /posts.json
  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @posts }
  end
end
end
  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
   #if request.path != post_path(@post)
   #    redirect_to @post, status: :moved_permanently
   #  end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    5.times { @post.assets.build }
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    5.times { @post.assets.build }
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/posts/_form.html.erb
<%= form_for(@post, :html => { :multipart => true }) do |f| %>


  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  
  <%= f.fields_for :assets do |asset_fields| %>
  	
  <% if asset_fields.object.new_record? %>
	
  <p>
	  <%= asset_fields.file_field :asset %>
  </p>
  
  <% end %>
  <% end %>
  
  <%= f.fields_for :assets do |asset_fields| %>
  
  <% unless asset_fields.object.new_record? %>
  
  <p>
	  <%= link_to image_tag(asset_fields.object.asset.url(:thumb)), asset_fields.object.asset.url(:original)%>
	  <label>
	  <%= asset_fields.check_box :_destroy %><%= t(".Destroy") %>
  </label>
  </p>
	  <% end %>
	  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
  
 
<h1><%= t(".Editing") %>: <%= @post.title %></h1>



<%= render 'form' %>

<%= link_to t(".Show"), @post %> |
<%= link_to t(".Back"), posts_path %>

app/views/posts/index.html.erb
<h1>Post</h1>

<% if can? :create, @post %>
<p><%= link_to t(".new"), new_post_path %></p>
<% end %>

<div id="tag_cloud"><%= t".Tags Cloud" %>
  <% tag_cloud Post.tag_counts, %w{s m l} do |tag, css_class| %>
   <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

<hr />

<div id="post">
  <% @posts.each do |post| %>
  
    <h2><%= link_to post.title, post %></h2>
	
    <%= truncate_html simple_format post.content %>
	
	<p>Tags: <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
	
	<div id="comments-count">
		<%= t(".Comments") %> <%= "(#{post.comments.count})" %>
	</div>
	
	<% if can? :update, @post %>
    <p><%= link_to t(".edit"), edit_post_path(post) %></p>
	<% end %>
	
	<% if can? :destroy, @post %>
	<p><%= link_to t(".destroy"), post, method: :delete, data: { confirm: t(".Are you sure?") } %></p>
  <% end %>
  
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
 
<p>
  <b><%= t(".Name") %>:</b>
  <%= @post.name %>
</p>
 
<p>
  <b><%= t(".Title") %>:</b>
  <%= @post.title %>
</p>
 
<p>
  <b><%= t(".Content") %>:</b>
  <%= @post.content %>
</p>

 <p>Tags: <%= raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
 
 <div class="thumb">
	 <p>
	     <b><%= t(".Pictures") %>:</b>
  
	 </p>
 <% for asset in @post.assets %>

<%= link_to image_tag(asset.asset.url(:thumb)), asset.asset.url(:original), :class => 'lightview'%>

 <% end %>
 
</div>

<% if can? :read, @comment %>
<h2><%= t(".Comments") %></h2>
<%= render @post.comments %>
<% end %>

<% if can? :create, @comment %>
<h3><%= t(".Add a comment") %></h3>
<%= render "comments/form" %>
<% end %>

<% if can? :update, @post %>
<%= link_to t(".Edit Post"), edit_post_path(@post) %> |
<% end %>

<%= link_to t(".Back to Posts"), posts_path %>