config/routes.rb
OctoDangerzone::Application.routes.draw do
  
  resources :galleries do
    resources :pictures
  end

  resources :posts do
    resources :comments
  end

  get 'tags/:tag' => 'posts#index', as: :tag

  get "home/index"

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :path => "d"
  resources :users
  
  get 'galleries/fragglerne', :as => 'fragglerne'

  namespace :admin do
  	match '/' => 'users#index'
  	resources :users
  end
  
   match '/profiles/dashboard' => 'profiles#dashboard', :as => :user_root
   resources :profiles, :only => [:dashboard]
  
   scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
   root :to => 'home#index'
 end
  
   match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
   match '', to: redirect("/#{I18n.default_locale}")
  
 
  

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :name
  validates :name,  :presence => true
  has_many :pictures, :dependent => :destroy
  
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
  def should_generate_new_friendly_id?
      new_record?
    end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  load_and_authorize_resource
  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
    #if request.path != gallery_path(@gallery)
    #    redirect_to @gallery, status: :moved_permanently
    #  end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<h1><%= t ".title" %></h1>

 

<% @galleries.each do |gallery| %>
  
    <%= gallery.name %>
    
    <%= link_to t(".Show"), gallery %>
    
	<% if can? :update, @gallery %>
    <%= link_to t(".edit"), edit_gallery_path(gallery) %>
	<% end %>
	
	<% if can? :destroy, @gallery %>
    <%= link_to t(".destroy"), gallery, method: :delete, data: { confirm: t(".Are you sure?") } %>
	<% end %>
  
<% end %>


<br />
<% if can? :create, @gallery %>
<%= link_to t(".New Gallery"), new_gallery_path %>
<% end %>

app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Gallery:</b>
  <h2><%= @gallery.name %></h2>
</p>

<% @gallery.pictures.each do |picture|%>
<p>
  <b>Picture name:</b>
  <%= picture.name %>
</p>

<%= link_to (image_tag (picture.image_url(:thumb))), picture.image.url(:original), :class => 'lightview' %>

<p>
	<% if can? :destroy, @picture %>
<%= link_to 'Destroy Picture', [picture.gallery, picture],
             :confirm => 'Are you sure?',
             :method => :delete %>
		 </p>
		 <% end %>
 <% end %>
 <% if can? :create, @picture %>
<h2>Add a picture:</h2>
<%= render "pictures/form" %>
<% end %>
<% if can? :update, @gallery %>
<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<% end %> 
<%= link_to 'Back', galleries_path %>