config/routes.rb
OctoDangerzone::Application.routes.draw do
  
  resources :galleries do
    resources :pictures
  end

  resources :posts do
    resources :comments
  end

  get 'tags/:tag' => 'posts#index', as: :tag

  get "home/index"

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :path => "d"
  resources :users
  
  get 'galleries/fragglerne', :as => 'fragglerne'

  namespace :admin do
  	match '/' => 'users#index'
  	resources :users
  end
  
   match '/profiles/dashboard' => 'profiles#dashboard', :as => :user_root
   resources :profiles, :only => [:dashboard]
  
   scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
   root :to => 'home#index'
 end
  
   match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
   match '', to: redirect("/#{I18n.default_locale}")
  
 
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user
    if user.role? :admin
      can :manage, :all
    elsif user.role? :registered
      can :manage, Post do |post|
        post.user_id == user.id
      end
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_ability.rb
class AdminAbility
  include CanCan::Ability
  def initialize(user)
    if user.role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    
  end
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  attr_accessible :asset_content_type, :asset_file_name, :asset_file_size, :asset_updated_at, :post_id, :asset
  belongs_to :post
  has_attached_file :asset, :styles => { :large => "640x480>", :thumb => "100x100>" }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :name
  validates :name,  :presence => true
  has_many :pictures, :dependent => :destroy
  
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
  def should_generate_new_friendly_id?
      new_record?
    end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :gallery
  attr_accessible :name, :image
  mount_uploader :image, ImageUploader
  
  validates :name,  :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  attr_accessible :content, :name, :title, :tag_list, :assets_attributes

  acts_as_taggable
  
  validates :name,  :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
                    
  has_many :comments, :dependent => :destroy

  has_many :assets
  accepts_nested_attributes_for :assets, :allow_destroy => true

  
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :role_ids, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :setup_role
  has_and_belongs_to_many :roles
  def role?(role)
      return !!self.roles.find_by_name(role.to_s.camelize)
  end
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :role_ids
  # attr_accessible :title, :body
  def setup_role 
    if self.role_ids.empty?     
      self.role_ids = [3] 
    end
    
  

end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end
 
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  load_and_authorize_resource
  def create
    @gallery = Gallery.find(params[:gallery_id])
    @picture = @gallery.pictures.create(params[:picture])
    redirect_to gallery_path(@gallery)
  end
 
  def destroy
    @gallery = Gallery.find(params[:gallery_id])
    @picture = @gallery.pictures.find(params[:id])
    @picture.destroy
    redirect_to gallery_path(@gallery)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
   # GET /posts
  # GET /posts.json
  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @posts }
  end
end
end
  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
   #if request.path != post_path(@post)
   #    redirect_to @post, status: :moved_permanently
   #  end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    5.times { @post.assets.build }
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    5.times { @post.assets.build }
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!

  def dashboard
    @user = User.find(current_user.id)
    if @user.role? :admin
      redirect_to admin_users_path, :notice => "Aloah Admin!"
    else
      respond_to do |format|
        format.html # dashboard.html.erb
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fragglerne</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav>
	<ul>
	<li>
		<%= link_to t(".Home"), root_path %>
	</li>
	<li>
		<%= link_to t(".Post"), posts_path %>
	</li>
	<li>
		<%= link_to t(".Gallery"), galleries_path %>
		<ul>
		<li>
		<%= link_to t(".Fragglerne"), fragglerne_path %>
		</li>
		</ul>
	</li>
	<% if can? :read, @user %>
	<li>
		<%= link_to t(".Profil"), user_root_path %>
	</li>
	<% end %> 
	</ul>
	
	</nav>
		<%- flash.each do |name, msg| -%>
	        <%= content_tag :div, msg, :id => "flash_#{name}" %>
	      <%- end -%>
	      
		  <div id="user_nav">
		    <% if user_signed_in? %>
		     <%= t ".signed in as" %> <%= current_user.username %>. <%= t ".Not you?" %>
		  	
		      <%= link_to t(".Sign out"), destroy_user_session_path %>
			  <%= link_to t(".Edit profile"), edit_user_registration_path %>
		    <% else %>
		      <%= link_to t(".Sign up"), new_user_registration_path %><%= t(".or") %>
		      <%= link_to t(".Sign in"), new_user_session_path %>
		    <% end %>
		  </div>
<%= yield %>


<div id="language-selector"><%= link_to_unless_current "English", locale: "en" %> |
	<%= link_to_unless_current "Dansk", locale: "da" %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fragglerne</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav>
	<ul>
	<li>
		<%= link_to t(".Home"), root_path %>
	</li>
	<li>
		<%= link_to t(".Post"), posts_path %>
	</li>
	<li>
		<%= link_to t(".Gallery"), galleries_path %>
		<ul>
		<li>
		<%= link_to t(".Fragglerne"), fragglerne_path %>
		</li>
		<li>
		
		</li>
		</ul>
	</li>
	<% if can? :read, @user %>
	<li>
		<%= link_to t(".Profil"), user_root_path %>
	</li>
	<% end %> 
	</ul>
	
	</nav>
	<%- flash.each do |name, msg| -%>
	        <%= content_tag :div, msg, :id => "flash_#{name}" %>
	      <%- end -%>
	      
		  <div id="user_nav">
		    <% if user_signed_in? %>
		     <%= t ".signed in as" %> <%= current_user.username %>. <%= t ".Not you?" %>
		  	
		      <%= link_to t(".Sign out"), destroy_user_session_path %>
			  <%= link_to t(".Edit profile"), edit_user_registration_path %>
		    <% else %>
		      <%= link_to t(".Sign up"), new_user_registration_path %><%= t(".or") %>
		      <%= link_to t(".Sign in"), new_user_session_path %>
		    <% end %>
		  </div>
<%= yield %>


<div id="language-selector"><%= link_to_unless_current "English", locale: "en" %> |
	<%= link_to_unless_current "Dansk", locale: "da" %>
</div>
</body>
</html>